### ISSUE TITLE
scrolling up doesn't work in EIN

### ISSUE THREAD

**Issue by julian-urban** [io12/good-scroll.el#7]
Scrolling up keeps jumping back to the cursor position in emacs ipython notebook, while scrolling down works very well and is super smooth across images (which I was trying to achieve). It seems like the cursor travels a few lines up when I scroll up and then gets stuck. I need to move the cursor to be able to scroll further up, so this breaks it for me unfortunately.

I would be very happy if this can be solved somehow, because it works super well on the down-scroll and makes it so much better to edit jupyter notebooks with plots.

**Comment by io12** [comment]
I think I know what you're talking about. Are you saying the cursor is at the top of the window and scrolling that would move it outside the window gets stuck?

Emacs seems to not like when the cursor goes outside the window. Good-scroll has code to move the cursor away from the top/bottom, but it's not that great code and also causes https://github.com/io12/good-scroll.el/issues/6.

**Comment by julian-urban** [comment]
Yeah that seems to be the issue, except that in my case the cursor is at the bottom of the window, but I guess that's the same thing then. Unfortunately I don't speak lisp or I would try to fix it ...

**Comment by io12** [comment]
The fix for https://github.com/io12/good-scroll.el/issues/6 (which I'm working on now), will probably also fix this.

**Comment by julian-urban** [comment]
Thanks, I tried out the new version in the fix-jump-back branch. Now scrolling up works perfectly, but scrolling down is broken :smile: the behavior is basically the inverse of before. Any way to get the best of both worlds? :laughing:

**Comment by io12** [comment]
I think I can reproduce this, or at least something similar. It seems like it's broken in a different kind of way though? Instead of freezing or jumping backwards, it jumps forwards.

**Comment by io12** [comment]
Can you check if e0059e5 (the latest commit on fix-jump-back I pushed just now) fixes this? You might need to change `good-scroll-point-jump` to 1 if the cursor jumps outside the window and causes an error.

**Comment by julian-urban** [comment]
Unfortunately, the commit doesn't fix scrolling down in EIN. However, I managed to get it to work (almost) perfectly by replacing the new code for the three `good-scroll--go-to-down` functions with the old code from [5e601c8](https://github.com/io12/good-scroll.el/commit/beac144c37227d23e5ceefb8ce1f45aa484ca5c9). I tried this because using the latter commit, scrolling down worked and scrolling up was broken. I don't know which part of the code causes the problem, but doing it this way, both directions appear to work well. The only remaining issue seems to be that scrolling down across images jumps back by one line. Maybe that can be solved as well, but I could live with that and am already happy now that it works :smile:

**Comment by io12** [comment]
Interesting. The changes to the `good-scroll--go-to-down` functions are to fix https://github.com/io12/good-scroll.el/issues/6. What you're talking about might be something else, then. Can you post a Jupyter notebook to reproduce the issue? This could be a good excuse for me to try EIN :)

**Comment by io12** [comment]
> Can you post a Jupyter notebook to reproduce the issue?
@julian-urban Any updates on this? I know you have a local patch working, but I want to be able to push a proper fix that works in all cases.

**Comment by julian-urban** [comment]
Sorry about not getting back to you, it's still on my ToDo list, but has kinda gone under in the past few weeks. I will put together a minimal working version. Also I think my "fix" didn't fix it completely, which was annoying me to the point that I have good-scroll currently deactivated again... but I definitely want to have it, scrolling past images is really bad in vanilla emacs. I hope to be able to send you something soon.

**Comment by julian-urban** [comment]
Hi, sorry for not getting back to you for so long. I finally put together a (more or less) minimal config file and two test notebooks containing some example plots, one for ein and one for ob-ein (org mode integration). Scrolling down works fairly well with the newest version of good-scroll that I just pulled, but scrolling up is still broken when trying to scroll past the plots. I zipped the 3 files and put them in my gdrive: https://drive.google.com/file/d/1BYr4kIYRfTrPboroilJSkjaiKdbqfoHW/view?usp=sharing

**Comment by io12** [comment]
I can reproduce the issue with this, thanks!

**Comment by io12** [comment]
Since https://github.com/io12/good-scroll.el/commit/c237000a506b3e2808406172970a14ba35f21c49, the issue is fixed for the ob-ein one. For the ein one, it looks like the vscroll is being reset to zero when the cursor moves between cells. I remember looking into this earlier and finding that vscroll was being set inside the display backend instead of manually with `set-window-vscroll`, which makes it harder to avoid. It might be possible to save and restore the vscroll at all cursor movement, though.

**Comment by io12** [comment]
> It might be possible to save and restore the vscroll at all cursor movement, though.

It looks like hooking `window-scroll-functions` works, so this should be fixed soon.

**Comment by io12** [comment]
Should be fixed now :)
